name: Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.0

      - name: Install Android SDK platforms and build tools
        run: |
          sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build Gradle project
        run: ./gradlew assembleRelease  # Ganti dengan assembleDebug untuk build versi debug

      - name: Upload APK as an artifact (optional)
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: app/build/outputs/apk/release/app-release.apk  # Sesuaikan dengan path APK Anda
